### ISSUE TITLE
settings IS Error 500

### ISSUE THREAD

**Issue by codyliou** [tdvsdv/unread_issues#10]
My Settings plugin IS find Error

Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"unread_issues"}
  Current user: cody (id=3)
  Rendered plugins/unread_issues/app/views/settings/_unread_issues_settings.html
.erb (11.0ms)
  Rendered settings/plugin.html.erb within layouts/admin (13.0ms)
Completed 500 Internal Server Error in 22ms

ActionView::Template::Error (undefined method `settings' for nil:NilClass):
    1: <%- defaults = Redmine::Plugin::registered_plugins[:advanced_roadmap].set
tings[:default] -%>
    2: <% frequency=@settings['frequency'].to_i || defaults['frequency'].to_i%>
    3: <% decay=@settings['decay'].to_i || defaults['decay'].to_i%>
    4:
  app/views/settings/plugin.html.erb:6:in`block in _1dc6400beec42b3c1fc4d54bf32
8a2db'
  app/views/settings/plugin.html.erb:4:in `_1dc6400beec42b3c1fc4d54bf328a2db'

**Comment by tdvsdv** [comment]
We fixed it. 

Note that this plugin is better to use along with our skin https://github.com/tdvsdv/redmine_alex_skin. We also recommend to use our plugin Luxury buttons http://rmplus.pro/luxury_buttons. The plugin is very useful for those who use Redmine.
